### ISSUE TITLE
Trait reference internal error

### ISSUE THREAD

**Issue by 5hayanB** [chipsalliance/chisel#3381]
I have a trait `Config` defined as follows

```scala
package configs


trait Configs {
  val XLEN         : Int = 32
  val ByteWidth    : Int = 8
  val HalfWordWidth: Int = 16
  val RegAddrWidth : Int = 5
  val OpcodeWidth  : Int = 7
  val Funct3Width  : Int = 3
  val Funct7Width  : Int = 7

  val WMaskWidth: Int = 4
  val AddrWidth : Int = 8
}
```

The module that I am importing this trait is as follows

```scala
package core.execute_stage

import chisel3._,
       chisel3.util._
import configs.Configs,
       core.decode_stage.DMemCtrl,
       core.pipeline_regs.RegDEIO


class DMemAlignerIO extends Bundle with Configs {
  val alu : SInt     = Flipped(new ALUIO().out)
  val ctrl: DMemCtrl = Flipped(new RegDEIO().dMemCtrl)
  val data: SInt     = Flipped(new RegDEIO().intData(1))
}


class DMemAligner extends Module with Configs {
  val io: DMemAlignerIO = IO(new DMemAlignerIO)

  val offset: UInt = io.alu(1, 0)
  val addr  : UInt = io.alu(AddrWidth + 1, 2)
  val align : Bool = RegInit(0.B)

  val byte    : UInt = WireInit(io.data(ByteWidth - 1, 0))
  val halfWord: UInt = WireInit(io.data(HalfWordWidth - 1, 0))
}
```

On compiling this with sbt, I am receiving the following error

```sbt
chisel3.package$ChiselException: Internal Error! Could not get ref for 'SInt<32>[3]' @[src/main/scala/core/execute_stage/DMemAligner.scala 24:40]! 'SInt<32>[3]' was defined in module 'core.execute_stage.DMemAligner@5a765e3c'. This is a bug in Chisel, please file an issue at 'https://github.com/chipsalliance/chisel3/issues/new'
[info]   at chisel3.internal.throwException$.apply(Error.scala:93)
[info]   at chisel3.internal.firrtl.Converter$.reportInternalError(Converter.scala:33)
[info]   at chisel3.internal.firrtl.Converter$.$anonfun$getRef$1(Converter.scala:40)
[info]   at scala.Option.getOrElse(Option.scala:201)
[info]   at chisel3.internal.firrtl.Converter$.getRef(Converter.scala:37)
[info]   at chisel3.internal.firrtl.Converter$.convert(Converter.scala:67)
[info]   at chisel3.internal.firrtl.Converter$.convert(Converter.scala:75)
[info]   at chisel3.internal.firrtl.Converter$.$anonfun$convertSimpleCommand$1(Converter.scala:116)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[info]   ...
```

Tracking the problem, I found that the variable `ByteWidth` is not being referenced, though I have already inherited the trait `Config` in the class definition. What could be the problem?

sbt version = 1.7.1
chisel version = 3.6.0
scala version = 2.13.10

**Comment by 5hayanB** [comment]
I looked into it further and found out the referencing error was not about the trait, rather the `data` variable in the `DMemAlignerIO`. Chisel could not reference `RegDEIO().intData(1)`. I defined `intData` as a `Vector[SInt]` but it seems that referencing a "slice" of a vector is not applicable in this way. I would like to know if there is work going on to implement referencing an element of a `Vector`.
